# Generated by Django 3.2 on 2022-01-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mybooksite', '0006_alter_book_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('books', models.ManyToManyField(blank=True, null=True, to='mybooksite.Book')),
            ],
        ),
    ]
