# Generated by Django 3.2 on 2022-01-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0006_alter_book_availability'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(blank=True, to='mybooksite.Book'),
        ),
    ]
