# Generated by Django 3.2 on 2022-02-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='book_img/'),
        ),
    ]
