# Generated by Django 3.2 on 2021-12-31 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0002_auto_20211231_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_img')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybooksite.book')),
            ],
        ),
    ]
