# Generated by Django 3.2 on 2021-12-31 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0003_auto_20211231_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='book_img'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookImage',
        ),
    ]
