# Generated by Django 3.2 on 2021-12-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0005_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'in_stock'), ('out_stack', 'out_of_stack')], max_length=10),
        ),
    ]
