# Generated by Django 3.2 on 2022-01-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0006_alter_book_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(),
        ),
    ]
