# Generated by Django 3.2 on 2022-01-11 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0007_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mybooksite.category'),
            preserve_default=False,
        ),
    ]
