# Generated by Django 3.2 on 2022-01-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0012_auto_20220111_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='book',
        ),
        migrations.AddField(
            model_name='category',
            name='books',
            field=models.ManyToManyField(blank=True, to='mybooksite.Book'),
        ),
    ]
