# Generated by Django 3.2 on 2022-01-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0013_auto_20220111_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='categories', to='mybooksite.Book'),
        ),
    ]
