# Generated by Django 3.2 on 2022-01-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0014_alter_category_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='book_thumbnails'),
        ),
    ]
