# Generated by Django 3.2 on 2022-01-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0015_book_img_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='img_thumbnail',
            new_name='thumbnail',
        ),
    ]
