# Generated by Django 3.2 on 2022-01-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0016_rename_img_thumbnail_book_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='book_img'),
        ),
    ]
