# Generated by Django 3.2 on 2022-01-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0017_alter_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.BooleanField(choices=[(1, 'in_stock'), (0, 'out_of_stack')], max_length=1),
        ),
    ]
