# Generated by Django 3.2 on 2022-01-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0019_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.CharField(choices=[('in stack', 'in_stock'), ('out of stack', 'out_of_stack')], max_length=13),
        ),
    ]
