# Generated by Django 3.2 on 2022-01-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0020_alter_book_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.CharField(choices=[('in stock', 'in_stock'), ('out of stock', 'out_of_stock')], max_length=13),
        ),
    ]
