# Generated by Django 3.2 on 2022-01-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksite', '0021_alter_book_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='availability',
        ),
    ]
